### ISSUE TITLE
Undefined behavior comparing pointer in sync_mutex.cpp

### ISSUE THREAD

**Issue by pamarcos** [cubiclesoft/cross-platform-cpp#3]
When compiling sync_mutex with a modern compiler (GCC 5.3+) and -Wextra, it detects an error:

```
third_party/cross-platform-cpp/sync/sync_mutex.cpp: In member function 'bool CubicleSoft::Sync::Mutex::Create(const char*)':
third_party/cross-platform-cpp/sync/sync_mutex.cpp:159:20: error: ordered comparison of pointer with integer zero [-Werror=extra]
    if (MxOwnerID > 0)
                    ^
cc1plus: all warnings being treated as errors
```

This can me easily fixed by changing it to:
    `if (MxOwnerID != 0)`

I am only compiling sync_mutex, sync_shared_mem and sync_utils so it may be worth it to check the rest of the files using `-pedantic -Wall -Wextra -Werror`

**Comment by cubiclesoft** [comment]
I've never liked -Werror.  It's overkill to stop running a compiler when a warning is encountered..

That section of code will likely never execute in most (sane) programs as it is for reusing a mutex object.

After looking at the code for a bit, it should probably be:

````if (MxCount > 0)````

Otherwise, the code ends up checking MxOwnerID twice and comparisons to pthread_t should be strictly comparing to other pthread_t types.

Thanks for pointing it out!  Fixed for all platforms.
