### ISSUE TITLE
utf8_file_dir: GetAbsoluteFilename returns false when path has "../" in it

### ISSUE THREAD

**Issue by lordadamson** [cubiclesoft/cross-platform-cpp#4]
so it may handle relative paths as long as they do not contain .. in them.

```
test: CubicleSoft::UTF8::Dir::Mkdir("../tests/testDirectory");
```
returns false and fails at the sanity check. given that the tests directory does exist.

**Comment by cubiclesoft** [comment]
This is by design.  `File::GetAbsoluteFilename()` does not accept relative traversal paths.  The sanity check stage verifies that no relative paths are still being referenced after all resolutions are complete.  Instead, use `File::Realpath()` to perform a relative to absolute path conversion for the relative portion of the path (i.e. ".."). Then carefully concatenate "/tests/testDirectory" to the result and THEN call `Dir::Mkdir()`.  Any attempt to bypass the sanity check in the library will likely introduce subtle security vulnerabilities into your application, particularly on Windows.

Unless you are creating a ton of directories via relative paths that you can't cache a full path to, `Dir::Mkdir()` is the only part of the UTF8 File/Dir class code where concatenation is required at the application level to handle relative paths that reference parent directories since at least one path part might not exist yet.  Correctly handling ".." isn't simply a matter of altering string elements - there are lots of edge cases to handle (e.g. symlink traversal).

I've closed the associated pull request.

**Comment by lordadamson** [comment]
Okay I guess I'll just do as suggested. Would have been great if there was a way to have Mkdir handle the whole thing though.

So yeah, thanks and great library by the way. I've enjoyed using it ❤️

**Comment by cubiclesoft** [comment]
After some more thought on the matter, I decided to add a semi-lengthy comment to `utf8_file_dir.h` to the effect of what we discussed in this issue so that other people can avoid similar problems without having to scour the issue tracker.
